./client $(ps | grep server | awk 'NR==1 {printf $1}') "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean quis libero quis quam vulputate tristique eget id turpis. Morbi quis faucibus lacus, quis consectetur erat. Morbi quis rhoncus felis. Maecenas semper mi est, at accumsan eros molestie porttitor. Vestibulum faucibus est eget velit faucibus, vel vestibulum ligula gravida. Quisque pulvinar non tortor ac tristique. Nulla rutrum massa sit amet ex consequat porttitor. Nunc sit amet urna et ipsum pellentesque pellentesque. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc malesuada eu massa non suscipit. Duis massa ante, condimentum et laoreet at, tristique eu augue. Nunc placerat lacus ac elit viverra, et porttitor lorem dapibus. Mauris arcu justo, suscipit condimentum dui vitae, varius posuere nisl. Nullam rhoncus dolor id dolor efficitur laoreet in sed nulla.

Aenean in semper libero. Suspendisse convallis erat eu hendrerit aliquam. Vestibulum suscipit sapien ac mauris interdum, nec mollis ante rutrum. Integer finibus ligula libero, a ullamcorper neque semper ac. In nec lectus accumsan, eleifend magna eget, auctor augue. Aenean dictum accumsan elementum. Phasellus nec metus aliquet, sodales arcu quis, iaculis augue. Morbi tellus tellus, fermentum vitae consequat in, laoreet ut tellus.

Mauris posuere enim vitae turpis auctor rutrum. Etiam urna urna, elementum at tellus nec, tempor porttitor ante. Nunc sit amet scelerisque sem. Quisque auctor blandit felis, eget vulputate lacus lobortis vel. Nam ut efficitur arcu. Etiam eget tellus nunc. Proin sed diam a ligula venenatis egestas. Maecenas laoreet augue vulputate arcu cursus consequat.

Nam euismod erat eget suscipit auctor. Pellentesque eros nibh, commodo sed turpis ac, molestie posuere quam. Sed sit amet lorem nec purus interdum pulvinar in ut elit. Vestibulum pulvinar, turpis vitae vulputate elementum, neque nisl dapibus neque, a molestie mauris lectus eget nunc. Fusce eget egestas enim. Aenean eu ornare metus. Nullam egestas, nisl volutpat sodales lacinia, nunc arcu dictum dolor, sed blandit massa diam ut felis. Vivamus egestas a metus eget ultrices. Nam pharetra, nisi at vehicula malesuada, tortor odio malesuada metus, non vulputate sapien magna non elit. Integer cursus sagittis auctor. Phasellus viverra velit libero, id vulputate felis posuere id. Praesent tristique nisi est, vel aliquam nibh iaculis sed. Morbi mauris orci, cursus vel erat et, tempus mollis dui. Praesent sagittis justo eget lectus fringilla, eu ornare lectus pretium.

Phasellus eget nunc ac diam lacinia consequat ut at risus. Nullam sit amet tellus vitae erat dictum lacinia. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse lorem augue, mollis sit amet laoreet mattis, porta a sapien. Interdum et malesuada fames ac ante ipsum primis in faucibus. In hac habitasse platea dictumst. Vivamus tempor suscipit risus, quis pellentesque augue interdum vitae. Integer tempus rhoncus risus sed finibus. Suspendisse potenti. Nulla facilisi. Duis at pretium tellus. Aenean fringilla tellus sed leo lobortis, at pretium urna laoreet. Nulla sit amet ultricies nisi, in condimentum orci. Aliquam viverra sapien vel molestie placerat.

Quisque dapibus aliquet iaculis. Donec dignissim consequat lorem. In nisi velit, egestas et magna nec, faucibus posuere neque. Aliquam ut odio tempor, aliquet nulla et, vulputate lectus. Proin faucibus dolor vel gravida rutrum. Aliquam erat volutpat. Curabitur laoreet nisi non sollicitudin sollicitudin. Quisque imperdiet orci sit amet erat lobortis, vitae porta arcu eleifend. Donec mattis nunc at nisi tincidunt, at blandit justo maximus. Praesent finibus mi odio, et posuere nisl eleifend interdum. Donec aliquet sapien ac bibendum blandit. Nulla mi elit, porta sit amet tincidunt sed, vulputate eget augue. Fusce tempor odio quis ex lobortis, ut pretium mauris consequat. Nullam eget risus sed magna pretium vehicula non a orci. Mauris quis sapien interdum, consectetur diam in, placerat eros.

Etiam venenatis placerat est, sed aliquet tortor pharetra id. Pellentesque efficitur, augue sit amet dictum sollicitudin, nunc mi consequat quam, in efficitur diam sem vel sapien. Etiam sed orci quis lacus fringilla mollis. Donec arcu sapien, iaculis sit amet dignissim id, vulputate eu elit. Suspendisse volutpat velit vitae ex congue ultricies. Nullam laoreet massa nec ex viverra eleifend. Morbi et mollis erat, non iaculis eros. Morbi quis pulvinar metus. Etiam sit amet porttitor felis, ut laoreet tortor. Phasellus justo lorem, euismod ut odio in, fermentum eleifend mi.

Proin quis felis ante. Nulla eu tempus est. Morbi ut arcu ac dolor iaculis aliquam. Proin bibendum enim augue, id mollis mauris bibendum non. Nulla cursus odio tortor, vel posuere metus vulputate quis. Phasellus condimentum molestie quam, ut condimentum metus molestie vitae. Donec dictum eros in diam faucibus fermentum. Vestibulum cursus purus et massa tempor, porttitor imperdiet magna gravida. Nulla rhoncus ipsum nec tellus blandit, eget consequat odio facilisis. Curabitur a lacus in odio pretium varius nec eget est. Aenean blandit pretium purus vel suscipit.

Nullam quam ex, dignissim nec dolor vel, ornare eleifend velit. Sed euismod iaculis dapibus. Nullam id massa feugiat, consequat arcu non, lacinia mauris. Sed ac orci vitae diam venenatis convallis. Pellentesque eget efficitur tellus. Quisque rutrum venenatis tristique. Duis faucibus mi ac ex vulputate, in iaculis nunc commodo. Suspendisse nec gravida elit. Duis sapien nisl, pulvinar aliquam tempor ut, fermentum non felis.

Sed sagittis est a ligula convallis molestie. Vivamus tincidunt, sapien eu faucibus euismod, metus est porttitor leo, id varius leo arcu vitae ligula. Proin interdum iaculis eros in sollicitudin. Suspendisse tincidunt in libero in pharetra. Praesent libero magna, mattis sed nibh sit amet, commodo laoreet elit. Praesent tempor augue lectus, vel molestie dolor consectetur sed. Sed posuere quam condimentum, eleifend libero in, laoreet libero. Nulla quis nibh dapibus, consequat nisl nec, sollicitudin turpis. Ut elementum pharetra purus, nec tristique nibh elementum quis. Aenean in tellus ipsum. Integer porta metus sit amet purus accumsan, in condimentum justo lobortis. Cras efficitur lacus quam, eget interdum mi finibus ut. Phasellus ornare finibus ultrices. Donec eu risus a metus faucibus porta vel ac mi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

Nam efficitur dolor elit. Aenean gravida elementum magna vitae accumsan. Donec euismod ullamcorper purus, sed accumsan massa ultrices at. Nulla facilisi. Curabitur ullamcorper diam sit amet lorem porttitor consequat. Proin feugiat tempor venenatis. Sed tristique diam mauris, quis tempus elit laoreet sit amet. Mauris id luctus massa.

Mauris euismod dignissim consequat. Sed posuere sem sit amet sem laoreet commodo id vel dolor. Quisque dignissim maximus turpis tempor volutpat. Integer at arcu tempus, dignissim risus sed, iaculis dolor. Vestibulum luctus augue et nisl pellentesque convallis. Aliquam erat volutpat. Nulla pharetra feugiat elit in gravida. Nunc convallis metus in augue faucibus gravida ut eget eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Phasellus vel porttitor metus. Quisque porttitor lectus purus. Nulla in aliquam enim. In hac habitasse platea dictumst.

Curabitur id ipsum et mi dictum accumsan. Pellentesque nunc nunc, pretium vitae nisi sit amet, scelerisque suscipit metus. Praesent tincidunt libero enim, non iaculis nisl rutrum et. Maecenas id justo interdum turpis faucibus porttitor ac eget eros. Morbi a arcu lobortis, tempus lorem eget, consequat arcu. Quisque sit amet dolor a odio placerat blandit sit amet id nisi. Suspendisse non risus nec magna blandit lobortis.

Praesent sapien massa, tempus nec ullamcorper in, tincidunt vitae diam. Pellentesque pulvinar nibh euismod sapien lacinia, ac feugiat nunc cursus. Duis tincidunt volutpat ipsum, sed iaculis erat imperdiet vel. Quisque id arcu leo. Sed magna nisi, auctor sit amet ante elementum, convallis egestas augue. Phasellus rutrum mauris a velit fringilla, sed consequat metus interdum. Suspendisse pretium hendrerit eros in interdum. Integer porta, nibh sit amet faucibus blandit, orci nulla sagittis augue, non sagittis mi erat vitae enim. Morbi sagittis diam felis, vitae lacinia magna varius quis. Aliquam quis sapien sapien. Etiam euismod gravida urna ut ullamcorper.

Suspendisse viverra justo vitae velit tempus, id ultrices dui sodales. Quisque bibendum mattis ex sit amet tincidunt. Phasellus finibus tellus dapibus vestibulum ultricies. Phasellus felis sapien, pulvinar nec velit eget, accumsan vehicula ante. Vestibulum ut aliquam nulla. Etiam non dolor consequat mi suscipit varius at ut massa. Nam mattis, erat in porttitor aliquam, ipsum arcu fermentum augue, a blandit ex diam in nunc. Praesent pharetra ipsum ut porta dignissim. Maecenas erat turpis, gravida at odio in, semper pharetra elit. Vivamus nunc ligula, ultrices vehicula elit at, finibus venenatis nisi. Sed pretium turpis eget varius maximus. Curabitur in risus euismod, mattis tellus a, congue nibh. Morbi eget neque at libero dapibus volutpat et sed erat. Sed egestas in dolor vel malesuada.

Curabitur laoreet ipsum malesuada porttitor aliquet. Cras bibendum suscipit odio, at porta neque porta in. Curabitur tincidunt facilisis ante, sed interdum ligula. Sed tristique velit felis, quis suscipit lectus ornare et. Suspendisse dignissim aliquet sem, a commodo eros. Maecenas sagittis venenatis risus at hendrerit. Maecenas hendrerit vulputate orci pellentesque pellentesque. Pellentesque in diam eu sem efficitur sollicitudin. Suspendisse potenti. In condimentum, velit porta tempor ultrices, est justo facilisis enim, at dignissim tellus dui eu eros.

Praesent tempor turpis felis, vitae luctus quam dignissim vel. Etiam a mauris eget metus interdum elementum in ut mauris. Vivamus sodales suscipit sapien ut sollicitudin. Proin ante elit, mollis vitae malesuada ac, iaculis in ante. Proin nec magna malesuada, ullamcorper nunc laoreet, venenatis sem. Suspendisse orci ante, lobortis vitae eleifend non, semper ut est. Cras nec urna porta, iaculis leo eu, semper diam. Nulla et lacus in orci rutrum euismod. Nulla vel massa in ante faucibus sollicitudin. Maecenas viverra risus quis fermentum porttitor. Proin pellentesque posuere finibus. Vivamus ut justo vitae velit aliquet venenatis. Donec mattis sapien sem, at condimentum libero vehicula ac.

Praesent condimentum at turpis nec varius. Duis a lacus vel dolor tristique condimentum nec sit amet dui. Vestibulum laoreet sed sem nec euismod. Integer viverra, turpis in fringilla cursus, odio risus porttitor sem, nec bibendum diam felis sit amet dolor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer sodales fringilla molestie. Maecenas neque risus, bibendum a nulla ultricies, venenatis faucibus enim. Pellentesque sem tellus, porta vel nibh nec, maximus fringilla felis.

Quisque tristique ante nunc, in condimentum metus dapibus non. Suspendisse vestibulum, erat nec luctus tempus, erat felis consequat lorem, quis porta justo velit nec nibh. Proin eget lacinia urna. Donec vitae lectus porta, hendrerit nisi eu, pellentesque purus. Fusce iaculis interdum neque, quis lobortis mauris aliquam et. Nulla facilisi. Suspendisse potenti. Pellentesque eget ante est. Curabitur id mi aliquam neque mattis efficitur et at dolor. Nunc sit amet porta turpis.mahmoud"